apiVersion: apps/v1
kind: Deployment
metadata:
  name: fluxgate-edge
  namespace: fluxgate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fluxgate-edge
  template:
    metadata:
      labels:
        app: fluxgate-edge
    spec:
      containers:
        - name: edge
          image: keaz/flux-gate-edge:v1.0.2
          imagePullPolicy: Always
          env:
            - name: EDGE_CONFIG_FILE
              value: "/app/config.toml"
            - name: CLIENT_ID_UUID
              value: e6415dec-37ba-430e-914c-06faec0201c1
            - name: CLIENT_API_KEY
              value: WP08dqJdCkMS8XBjXngoaJQGv8PHg0eFYPZ5sOEPeYTAH5Qw
          ports:
            - containerPort: 8081
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "1000m"
          volumeMounts:
            - name: config-toml
              mountPath: /app/config.toml
              subPath: config.toml
      volumes:
        - name: config-toml
          configMap:
            name: fluxgate-edge-config
