apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: fluxgate

resources:
  - namespace.yaml
  - backend-deployment.yaml
  - backend-service.yaml
  - edge-deployment.yaml
  - edge-service.yaml
  - ui-deployment.yaml
  - ui-service.yaml
  - configmap-backend.yaml
  - configmap-edge.yaml
  - secret-db.yaml
  - tls-secret.yaml
  - ingress.yaml

labels:
  - pairs:
      app.kubernetes.io/managed-by: kustomize
      app.kubernetes.io/part-of: fluxgate

# Common annotations for all resources
commonAnnotations:
  version: v0.0.9-alpha-arm64
